title: x-gov forms
description: Cross Government Forms community
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
plugins:
  - jekyll-relative-links
  - jekyll-target-blank
relative_links:
  enabled:     true
  collections: false
footer_content: "You can contribute to the content by making a Pull Request at <a href=\"https://github.com/XGovFormBuilder/x-gov-form-community\">Github.</a>"
